export const projectsData = [
  {
    link: "https://barbellwhip.com/",
    title: "BarbellWhip",
    description: "An open source workout management app built with React Native, with the goal of improving readability of complex training programs that make use of big spreadsheets mid training session, of sports such as powerlifting and weightlifting. It currently features a program review page, a program editor and a RM(repetition max) and weight plate calculators.",
    img: "public/barbellwhip.webp",
    imgAlt: "BarbellWhip",
    imgWidth: 195,
    imgHeight: 400,
  },
  // {
  //   link: "https://weeb.wdias.dev",
  //   title: "Tsuuchi",
  //   description: "Anime watch list.",
  //   img: "",
  //   imgAlt: "",
  //   imgWidth: 0,
  //   imgHeight: 0,
  // },
  {
    link: "https://github.com/wdiasjunior/papibaquigrafo",
    title: "papibaquigrafo",
    description: "A CLI tool for personal use written in Go to download manga from various sites.",
    img: "",
    imgAlt: "",
    imgWidth: 0,
    imgHeight: 0,
  },
  {
    link: "#",
    title: "This website",
    description: "Built with Astro. Simple, fast and gets the job done.",
    img: "",
    imgAlt: "",
    imgWidth: 0,
    imgHeight: 0,
  },
  {
    link: "https://github.com/wdiasjunior/split-keyboard",
    title: "Split Ortholinear Keyboard",
    description: "A 87 key ortholinear split keyboard that uses 2 Pi Picos and the KMK firmware.",
    img: "",
    imgAlt: "",
    imgWidth: 0,
    imgHeight: 0,
  },
  {
    link: "https://wdias.dev/BarbellTracker/",
    title: "OpenCV.js Barbell Tracker",
    description: "This is my university gradutaion project. A JavaScript application for weightlifting video analysis that runs the OpenCV library directly in the browser, with the following functionalities: Barbell Path Tracker, Realtime Concentric Velocity, Realtime Acceleration, Realtime Horizontal Displacement.",
    img: "public/barbellTracker.webp",
    imgAlt: "Barbell Tracker",
    imgWidth: 227,
    imgHeight: 400,
  },
]
